{{- if eq $.Values.vault.existingSecret "" }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ $.Release.Name }}-werf-vault-sync"
type: Opaque
data:
  WERF_SECRET_KEY: {{ $.Values.vault.secretKey | b64enc }}
{{- end }}
