kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-gitlab
data:
  {{- range $config, $configData := .Values.config }}
  {{ $config }}: {{ tpl $configData $ | b64enc }}
  {{- end }}
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-gitlab-env
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ tpl $v $ | b64enc }}
  {{- end }}
type: Opaque
