apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab.fullname" . }}-config
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
type: Opaque
stringData:
  gitlab.rb: |
{{ .Values.gitlab.config | indent 4 }}
