apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ports.pages }}
      targetPort: pages
      protocol: TCP
      name: pages
    - port: {{ .Values.ports.registry }}
      targetPort: registry
      protocol: TCP
      name: registry
    - port: {{ .Values.ports.ssh }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
