apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitlab-http
  labels:
    app: {{ .Release.Name }}-gitlab
    {{- range $k, $v := .Values.services.http.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if .Values.services.annotations }}
  annotations:
    {{- range $k, $v := .Values.services.http.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: {{ .Values.services.http.port }}
      targetPort: {{ .Values.services.http.containerPort }}
  selector:
    app: {{ .Release.Name }}-gitlab

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitlab-https
  labels:
    app: {{ .Release.Name }}-gitlab
    {{- range $k, $v := .Values.services.https.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if .Values.services.annotations }}
  annotations:
    {{- range $k, $v := .Values.services.https.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.services.https.type }}
  ports:
    - name: https
      protocol: TCP
      appProtocol: https
      port: {{ .Values.services.https.port }}
      targetPort: {{ .Values.services.https.containerPort }}
  selector:
    app: {{ .Release.Name }}-gitlab

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitlab-ssh
  labels:
    app: {{ .Release.Name }}-gitlab
    {{- range $k, $v := .Values.services.ssh.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if .Values.services.annotations }}
  annotations:
    {{- range $k, $v := .Values.services.ssh.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.services.ssh.type }}
  {{- if eq .Values.services.ssh.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.services.ssh.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.services.ssh.loadBalancerIP }}
  {{- end }}
  ports:
    - name: ssh
      protocol: TCP
      appProtocol: ssh
      port: {{ .Values.services.ssh.port }}
      targetPort: {{ .Values.services.ssh.containerPort }}
  selector:
    app: {{ .Release.Name }}-gitlab

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitlab-registry
  labels:
    app: {{ .Release.Name }}-gitlab
    {{- range $k, $v := .Values.services.registry.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if .Values.services.annotations }}
  annotations:
    {{- range $k, $v := .Values.services.registry.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.services.registry.type }}
  {{- if eq .Values.services.registry.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.services.registry.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.services.registry.loadBalancerIP }}
  {{- end }}
  ports:
    - name: registry
      protocol: TCP
      appProtocol: registry
      port: {{ .Values.services.registry.port }}
      targetPort: {{ .Values.services.registry.containerPort }}
  selector:
    app: {{ .Release.Name }}-gitlab
