kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-proxmox"
  {{- if .Values.service.labels }}
  labels:
    {{- range $k, $v := .Values.service.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "proxmox-operator.serviceSelectorLabels" . | nindent 6 }}
  type: ClusterIP
