kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.secret_name }}
  namespace: {{ $.Values.secret_namespace }}
data:
  tls.crt: >-
    {{ b64enc($.Values.crt) }}
  tls.key: >-
    {{ b64enc($.Values.key) }}
type: Opaque
