apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci
  namespace: gitlab-runner

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $.Release.Name }}-ci"
  namespace: gitlab-runner
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    resourceNames:
      - ci-deploy-secret
    verbs:
      - 'get'
      - 'list'
      - 'watch'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $.Release.Name }}-ci"
  namespace: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: ci
    namespace: gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ $.Release.Name }}-ci"
