{{- range $cluster, $clusterData := .Values.clusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "cluster-%s" $cluster }}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ $cluster }}
  server: {{ $clusterData.server }}
  config: |
    {
      {{- if $clusterData.bearerToken }}
      "bearerToken": "{{ $clusterData.bearerToken }}",
      {{- end }}
      "tlsClientConfig": {
        "insecure": false,
        {{- if $clusterData.clientCertificateData }}
        "certData": "{{ $clusterData.clientCertificateData }}",
        {{- end }}
        {{- if $clusterData.clientKeyData }}
        "keyData": "{{ $clusterData.clientKeyData }}",
        {{- end }}
        "caData": "{{  $clusterData.certificateAuthorityData }}"
      }
    }
---
{{- end }}
