{{- if and ($.Values.global.installCrs) (eq $.Values.oidc.enabled "true") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: {{ $.Values.oidc.secretStore }}
    kind: SecretStore
  target:
    name: argocd-oidc-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  dataFrom:
    - extract:
        key: {{ $.Values.oidc.key }}
---
{{- end }}
