{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talos-dhcp-server.fullname" . }}
type: Opaque
stringData: {{ $.Values.config | toYaml | nindent 2 }}
---
{{- end }}
