{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-config"
type: Opaque
stringData: {{ $.Values.config | toYaml | nindent 2 }}
---
{{- end }}
