apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name "dhcp" }}
  labels:
    release: {{ $.Release.Name }}
    {{- range $k, $v := $.Values.service.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if $.Values.service.annotations }}
  annotations:
    {{- range $k, $v := $.Values.service.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "talos-dhcp-server.selectorLabels" . | nindent 4 }}
  type: {{ $.Values.service.type }}
  {{- if $.Values.service.sessionAffinity }}
  sessionAffinity: {{ $.Values.service.sessionAffinity }}
  {{- end }}
  {{- if $.Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $.Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if $.Values.service.loadBalancerIP }}
  loadBalancerIP: {{ $.Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: dhcp
      protocol: UDP
      port: 67
      targetPort: 67
    - name: tftp
      protocol: UDP
      port: 69
      targetPort: 69
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
