apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: {{ $.Release.Namespace }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $.Release.Name }}-gitlab-runner"
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - pods
      - pods/exec
      - pods/attach
      - pods/logs
      - secrets
      - services
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
      - update

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $.Release.Name }}-gitlab-runner"
  namespace: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ $.Release.Name }}-gitlab-runner"
