image:
  repository: gitlab/gitlab-ee
  tag: 16.0.3-ee.0

env: {}

readinessProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 10
  timeoutSeconds: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 10
  timeoutSeconds: 5
  periodSeconds: 10
startupProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 30
  timeoutSeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: 1
    memory: 2G
  limits: {}

config: {}
  # gitlab.rb: |
  #   external_url 'https://gitlab.example.domain'
  #   nginx['enable'] = false
  #   gitlab_workhorse['listen_network'] = "tcp"
  #   gitlab_workhorse['listen_addr'] = "0.0.0.0:9090"
  #   gitlab_rails['trusted_proxies'] = [ '10.0.0.0/8' ]
  #   gitlab_rails['gitlab_shell_ssh_port'] = 22
  #   gitlab_rails['time_zone'] = 'Europe/Moscow'
  #   gitlab_rails['registry_enabled'] = true
  #   gitlab_rails['registry_host'] = "registry.example.domain"
  #   gitlab_rails['registry_path'] = "/var/opt/gitlab/registry"
  #   gitlab_rails['omniauth_enabled'] = true
  #   gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
  #   gitlab_rails['omniauth_sync_profile_from_provider'] = ['openid_connect']
  #   gitlab_rails['omniauth_block_auto_created_users'] = false
  #   gitlab_rails['omniauth_providers'] = [
  #     {
  #       name: "openid_connect", # do not change this parameter
  #       label: "OpenID Connect", # optional label for login button, defaults to "Openid Connect"
  #       icon: "https://auth.example.domain/static/dist/assets/icons/icon_left_brand.svg",
  #       args: {
  #         name: "openid_connect",
  #         scope: ["openid", "groups", "profile", "email"],
  #         response_type: "code",
  #         issuer: "https://auth.example.domain/application/o/gitlab/",
  #         discovery: true,
  #         client_auth_method: "query",
  #         uid_field: "preferred_username",
  #         send_scope_to_token_endpoint: "false",
  #         pkce: true,
  #         client_options: {
  #           identifier: "",
  #           secret: "",
  #           redirect_uri: "https://gitlab.example.domain/users/auth/openid_connect/callback"
  #         }
  #       }
  #     }
  #   ]
  #   postgresql['shared_buffers'] = "256MB"
  #   sidekiq['concurrency'] = 1
  #   puma['worker_processes'] = 1
  #   web_server['external_users'] = ['www-data']
  #   grafana['enable'] = false
  #   letsencrypt['enable'] = false
  #   prometheus['enable'] = false
  #   node_exporter['enable'] = false
  #   redis_exporter['enable'] = false
  #   postgres_exporter['enable'] = false
  #   pgbouncer_exporter['enable'] = false
  #   prometheus_monitoring['enable'] = false
  #   prometheus['enable'] = false

  #   registry_external_url 'https://registry.example.domain'
  #   registry_nginx['enable'] = false
  #   registry['enable'] = true
  #   registry['registry_http_addr'] = "0.0.0.0:5005"

services:
  http:
    labels: {}
    annotations: {}
    type: ClusterIP
    port: 80
    containerPort: 80
  https:
    labels: {}
    annotations: {}
    type: ClusterIP
    port: 443
    containerPort: 443
  ssh:
    labels: {}
    annotations: {}
    type: LoadBalancer
    port: 22
    containerPort: 22
    externalTrafficPolicy: Local
    loadBalancerIP: ""
  registry:
    labels: {}
    annotations: {}
    type: LoadBalancer
    port: 5005
    containerPort: 5005
    externalTrafficPolicy: Local
    loadBalancerIP: ""

ingress:
  spec:
    ingressClassName: int
    hosts:
      - gitlab.example.domain
    tls:
      - hosts:
          - gitlab.example.domain
        secretName: example.domain

pvc:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: zfs
