{{- if $.Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-registrysecret"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $.Values.dockerconfigjson }}
{{- end }}
