{{- range $secret := $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ printf "%s-%s" $.Release.Name $.Values.release.name }}-{{ $secret.name }}"
  labels:
    release: {{ printf "%s-%s" $.Release.Name $.Values.release.name }}
    {{- range $k, $v := $secret.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- if $secret.annotations }}
  annotations:
    {{- range $k, $v := $secret.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
type: {{ $secret.type }}
stringData: {{ tpl ($secret.data | toYaml) $ | nindent 2 }}
---
{{- end }}
