kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-pdns-config"
data:
  pdns.conf: {{ tpl .Values.pdnsConf . | b64enc }}
  recursor.conf: >-
    {{ tpl .Values.recursorConf . | b64enc }}
type: Opaque
