{{- if not .Values.existingConfigSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "dhcp-operator.fullname" . }}
data:
  config.yaml: |
    {{ .Values.config | toYaml | b64enc }}
{{- end }}
