kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-dhcp-pxe"
  {{- if .Values.service.labels }}
  labels:
    {{- range $k, $v := .Values.service.labels }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: dhcp
      protocol: UDP
      port: 67
      targetPort: 6767
    - name: pxe
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{- include "dhcp-operator.selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}